### ISSUE TITLE
Fix semantic release

### ISSUE THREAD

**Issue by tthew** [eHealthAfrica/kazana-account-app#17]
Semantic release is broken due to a force push to `master`.

We need to make a manual release.

**Comment by gr2m** [comment]
- [ ] `npm publish` manually, temoprarily add `"version": "..."` to package.json for that
- [ ] `git tag vX.X.X` for same version that was published before
- [ ] Bonus: create a release for the tag at https://github.com/eHealthAfrica/kazana-account-app/releases
